### ISSUE TITLE
Parameter "-l" twice in docker-entrypoint.sh

### ISSUE THREAD

**Issue by fnwirth** [medizininformatik-initiative/distributed-analysis_datashield-qp#1]
In the file "ds_queue/docker-entrypoint.sh" the parameter "-l" is set twice when the default value of 20 is used since "-l" is also set in line 5:

https://github.com/medizininformatik-initiative/distributed-analysis_datashield-qp/blob/0eaa05233185fc46deb986780e1bce4486dd355b/ds_queue/docker-entrypoint.sh#L12

**Comment by juliangruendner** [comment]
i am not sure why this is a problem - it allows one to set a default value or and actual value if given.
the line 12 passes the in line 5 set log level on to the program which is started on the command line.
One could potentially use a different variable name, even though i would argue it is not necessary in this case

**Comment by fnwirth** [comment]
The problem is that the default value already includes "-l" whicht most likely translates to "[...] -l -l 20" when the default value is used which at least caused a problem on my machine when I set up qp.

**Comment by juliangruendner** [comment]
now i see, thank you. 
That is definitely an issue and will have to be fixed - the "-l" in line 5 should be removed

**Comment by sebmate** [comment]
Hi colleagues, thanks for reporting. I have just fixed it.
